// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseInputFiles():Promise<Array<string>>;

export function ChooseOutputDir(arg1:string):Promise<string>;

export function GetStatus():Promise<main.Status>;

export function OpenPath(arg1:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function StartExtract(arg1:main.ExtractOptions):Promise<void>;
