// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseInputFiles() {
  return window['go']['main']['App']['ChooseInputFiles']();
}

export function ChooseOutputDir(arg1) {
  return window['go']['main']['App']['ChooseOutputDir'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function StartExtract(arg1) {
  return window['go']['main']['App']['StartExtract'](arg1);
}
